import 'package:flutter/material.dart';

void main()=>runApp(const DemoApp());

const green=Color(0xFF0E7C66), deep=Color(0xFF123C35), bg=Color(0xFFF6F8F7), muted=Color(0xFF6E7774), line=Color(0xFFE5EBE8);

class DemoApp extends StatelessWidget{
  const DemoApp({super.key});
  @override Widget build(BuildContext context){
    return MaterialApp(
      debugShowCheckedModeBanner:false,
      locale:const Locale('ar'),
      builder:(c,w)=>Directionality(textDirection:TextDirection.rtl,child:w!),
      theme:ThemeData(
        useMaterial3:true,
        scaffoldBackgroundColor:bg,
        colorScheme:ColorScheme.fromSeed(seedColor:green),
        appBarTheme:const AppBarTheme(backgroundColor:bg,foregroundColor:deep,elevation:0,surfaceTintColor:Colors.transparent),
        filledButtonTheme:FilledButtonThemeData(style:FilledButton.styleFrom(backgroundColor:green,foregroundColor:Colors.white,minimumSize:const Size(48,52),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)))),
        outlinedButtonTheme:OutlinedButtonThemeData(style:OutlinedButton.styleFrom(foregroundColor:deep,minimumSize:const Size(48,52),side:const BorderSide(color:line),shape:RoundedRectangleBorder(borderRadius:BorderRadius.circular(16)))),
        inputDecorationTheme:InputDecorationTheme(filled:true,fillColor:Colors.white,border:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:const BorderSide(color:line)),enabledBorder:OutlineInputBorder(borderRadius:BorderRadius.circular(18),borderSide:const BorderSide(color:line))),
      ),
      home:const Shell(),
    );
  }
}

class P{
  final String t,l,p,type,purpose,img,sai;
  const P(this.t,this.l,this.p,this.type,this.purpose,this.img,this.sai);
}
const ps=[
  P('فيلا عصرية في حدة','صنعاء · حدة','85,000,000 ر.ي','فيلا','بيع','https://images.unsplash.com/photo-1600607687939-ce8a6c25118c?auto=format&fit=crop&w=1000&q=85','السعي 1% · على المشتري'),
  P('شقة واسعة قرب شارع الخمسين','صنعاء · بيت بوس','350,000 ر.ي / شهريًا','شقة','إيجار','https://images.unsplash.com/photo-1600566753190-17f0baa2a6c3?auto=format&fit=crop&w=1000&q=85','السعي 20% من شهر · على المستأجر'),
  P('أرض سكنية على شارع 20','صنعاء · شملان','42,500,000 ر.ي','أرض','بيع','https://images.unsplash.com/photo-1500382017468-9049fed747ef?auto=format&fit=crop&w=1000&q=85','السعي 1% · على البائع'),
  P('منزل مستقل قريب من الخدمات','إب · الظهار','58,000,000 ر.ي','منزل','بيع','https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1000&q=85','السعي 1% · على المشتري'),
];

void go(BuildContext c,Widget p)=>Navigator.push(c,MaterialPageRoute(builder:(_)=>p));

class Shell extends StatefulWidget{const Shell({super.key});@override State<Shell> createState()=>_ShellState();}
class _ShellState extends State<Shell>{
  int i=0;
  final pages=const [Home(),Messages(),Viewings(),Account()];
  @override Widget build(BuildContext c)=>Scaffold(
    body:IndexedStack(index:i,children:pages),
    bottomNavigationBar:NavigationBar(selectedIndex:i,onDestinationSelected:(v)=>setState(()=>i=v),indicatorColor:const Color(0xFFE7F4F0),backgroundColor:Colors.white,destinations:const [
      NavigationDestination(icon:Icon(Icons.apartment_outlined),selectedIcon:Icon(Icons.apartment,color:green),label:'العقارات'),
      NavigationDestination(icon:Icon(Icons.chat_bubble_outline),selectedIcon:Icon(Icons.chat_bubble,color:green),label:'الرسائل'),
      NavigationDestination(icon:Icon(Icons.calendar_month_outlined),selectedIcon:Icon(Icons.calendar_month,color:green),label:'المعاينات'),
      NavigationDestination(icon:Icon(Icons.person_outline),selectedIcon:Icon(Icons.person,color:green),label:'حسابي'),
    ]),
  );
}

class Home extends StatelessWidget{const Home({super.key});
  @override Widget build(BuildContext c)=>CustomScrollView(slivers:[
    SliverToBoxAdapter(child:Container(padding:EdgeInsets.fromLTRB(18,MediaQuery.of(c).padding.top+14,18,24),decoration:const BoxDecoration(gradient:LinearGradient(colors:[Color(0xFF0D6E5B),Color(0xFF124A40)]),borderRadius:BorderRadius.vertical(bottom:Radius.circular(34))),child:Column(children:[
      Row(children:[const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('مساء الخير 👋',style:TextStyle(color:Colors.white70,fontWeight:FontWeight.w700)),SizedBox(height:3),Text('ابحث عن مكان يناسبك',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:24))])),IconButton(onPressed:()=>go(c,const Notifications()),icon:const Icon(Icons.notifications_none,color:Colors.white))]),
      const SizedBox(height:18),
      InkWell(onTap:()=>go(c,const Search()),child:Container(height:58,padding:const EdgeInsets.symmetric(horizontal:14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18)),child:const Row(children:[Icon(Icons.search,color:deep),SizedBox(width:10),Expanded(child:Text('ابحث عن عقار، منطقة، نوع...',style:TextStyle(color:muted,fontWeight:FontWeight.w600))),Icon(Icons.tune,color:green)]))),
      const SizedBox(height:14),
      Row(children:[Expanded(child:_HeroBtn('للبيع',Icons.sell_outlined,()=>go(c,const Search()))),const SizedBox(width:8),Expanded(child:_HeroBtn('للإيجار',Icons.key_outlined,()=>go(c,const Search()))),const SizedBox(width:8),Expanded(child:_HeroBtn('الخريطة',Icons.map_outlined,()=>go(c,const MapPage())))]),
    ]))),
    SliverPadding(padding:const EdgeInsets.fromLTRB(18,18,18,0),sliver:SliverToBoxAdapter(child:Row(children:[Expanded(child:_Quick(Icons.favorite_border,'المفضلة',()=>go(c,const Favorites()))),Expanded(child:_Quick(Icons.compare_arrows,'المقارنة',()=>go(c,const Compare()))),Expanded(child:_Quick(Icons.insights_outlined,'المؤشرات',()=>go(c,const Market()))),Expanded(child:_Quick(Icons.bookmark_outline,'بحث محفوظ',()=>go(c,const SavedSearches())))]))),
    SliverPadding(padding:const EdgeInsets.fromLTRB(18,18,18,0),sliver:SliverToBoxAdapter(child:InkWell(onTap:()=>go(c,const Journey()),child:Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:const Color(0xFFEAF5F2),borderRadius:BorderRadius.circular(22)),child:const Row(children:[CircleAvatar(backgroundColor:green,child:Icon(Icons.route_outlined,color:Colors.white)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('رحلتي العقارية',style:TextStyle(fontWeight:FontWeight.w900,fontSize:17,color:deep)),SizedBox(height:3),Text('معاينة غدًا · اتفاق قيد المراجعة',style:TextStyle(color:muted,fontWeight:FontWeight.w600))])),Icon(Icons.arrow_back_ios_new,color:green,size:17)]))))),
    const SliverPadding(padding:EdgeInsets.fromLTRB(18,24,18,10),sliver:SliverToBoxAdapter(child:_Title('مختارة لك'))),
    SliverToBoxAdapter(child:SizedBox(height:270,child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:18),scrollDirection:Axis.horizontal,itemCount:3,separatorBuilder:(_,__)=>const SizedBox(width:12),itemBuilder:(c,i)=>SizedBox(width:255,child:PropCard(ps[i],big:true))))),
    const SliverPadding(padding:EdgeInsets.fromLTRB(18,24,18,10),sliver:SliverToBoxAdapter(child:_Title('قريبة من اختيارك'))),
    SliverPadding(padding:const EdgeInsets.fromLTRB(18,0,18,30),sliver:SliverList.separated(itemCount:ps.length,separatorBuilder:(_,__)=>const SizedBox(height:12),itemBuilder:(c,i)=>PropCard(ps[i]))),
  ]);
}

class _HeroBtn extends StatelessWidget{final String t;final IconData i;final VoidCallback f;const _HeroBtn(this.t,this.i,this.f);@override Widget build(BuildContext c)=>InkWell(onTap:f,child:Container(padding:const EdgeInsets.symmetric(vertical:11),decoration:BoxDecoration(color:Colors.white.withValues(alpha:.12),borderRadius:BorderRadius.circular(14),border:Border.all(color:Colors.white24)),child:Column(children:[Icon(i,color:Colors.white,size:20),const SizedBox(height:4),Text(t,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w800))])));}
class _Quick extends StatelessWidget{final IconData i;final String t;final VoidCallback f;const _Quick(this.i,this.t,this.f);@override Widget build(BuildContext c)=>InkWell(onTap:f,child:Column(children:[Container(width:50,height:50,decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:line)),child:Icon(i,color:green)),const SizedBox(height:6),Text(t,textAlign:TextAlign.center,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700))]));}
class _Title extends StatelessWidget{final String t;const _Title(this.t);@override Widget build(BuildContext c)=>Text(t,style:const TextStyle(fontSize:19,fontWeight:FontWeight.w900));}

class Img extends StatelessWidget{final String u;final double? w,h;const Img(this.u,{this.w,this.h,super.key});@override Widget build(BuildContext c)=>Image.network(u,width:w,height:h,fit:BoxFit.cover,errorBuilder:(_,__,___)=>Container(width:w,height:h,color:const Color(0xFFE8EEEB),child:const Icon(Icons.home_work_outlined,color:green,size:34)));}
class Tag extends StatelessWidget{final String t;const Tag(this.t,{super.key});@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:9,vertical:5),decoration:BoxDecoration(color:const Color(0xFFEAF5F2),borderRadius:BorderRadius.circular(999)),child:Text(t,style:const TextStyle(color:green,fontWeight:FontWeight.w900,fontSize:10)));}

class PropCard extends StatelessWidget{final P p;final bool big;const PropCard(this.p,{this.big=false,super.key});
  @override Widget build(BuildContext c){
    if(big)return InkWell(onTap:()=>go(c,Details(p)),child:Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(22),border:Border.all(color:line)),clipBehavior:Clip.antiAlias,child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Stack(children:[Img(p.img,w:double.infinity,h:145),Positioned(top:10,right:10,child:Tag(p.purpose))]),Padding(padding:const EdgeInsets.all(12),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.t,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:16)),const SizedBox(height:5),Text(p.p,style:const TextStyle(color:green,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(p.l,style:const TextStyle(color:muted,fontSize:12)),const SizedBox(height:7),Text('${p.type} · ${p.sai}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:11,fontWeight:FontWeight.w700))]))])));
    return InkWell(onTap:()=>go(c,Details(p)),child:Container(padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:line)),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(15),child:Img(p.img,w:116,h:104)),const SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Row(children:[Expanded(child:Text(p.t,maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontWeight:FontWeight.w900))),Tag(p.purpose)]),const SizedBox(height:5),Text(p.p,style:const TextStyle(color:green,fontWeight:FontWeight.w900)),const SizedBox(height:4),Text(p.l,style:const TextStyle(color:muted,fontSize:11)),const SizedBox(height:7),Text('${p.type} · ${p.sai}',maxLines:1,overflow:TextOverflow.ellipsis,style:const TextStyle(fontSize:10,fontWeight:FontWeight.w700))]))])));
  }
}

class Search extends StatefulWidget{const Search({super.key});@override State<Search> createState()=>_SearchState();}
class _SearchState extends State<Search>{int tab=0;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('البحث عن عقار')),body:Column(children:[Padding(padding:const EdgeInsets.all(16),child:TextField(decoration:InputDecoration(prefixIcon:const Icon(Icons.search),hintText:'صنعاء، حدة، فيلا...',suffixIcon:IconButton(onPressed:()=>filters(c),icon:const Icon(Icons.tune))))),Padding(padding:const EdgeInsets.symmetric(horizontal:16),child:SegmentedButton<int>(segments:const [ButtonSegment(value:0,label:Text('قائمة'),icon:Icon(Icons.list)),ButtonSegment(value:1,label:Text('خريطة'),icon:Icon(Icons.map_outlined))],selected:{tab},onSelectionChanged:(s)=>setState(()=>tab=s.first))),const SizedBox(height:10),Expanded(child:tab==0?ListView.separated(padding:const EdgeInsets.all(16),itemCount:ps.length,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(c,i)=>PropCard(ps[i])):const MapBody())]));}
void filters(BuildContext c)=>showModalBottomSheet(context:c,showDragHandle:true,builder:(_)=>Padding(padding:const EdgeInsets.all(20),child:Column(mainAxisSize:MainAxisSize.min,crossAxisAlignment:CrossAxisAlignment.start,children:[const Text('تصفية النتائج',style:TextStyle(fontSize:22,fontWeight:FontWeight.w900)),const SizedBox(height:14),const Wrap(spacing:8,runSpacing:8,children:[ChoiceChip(label:Text('بيع'),selected:true),ChoiceChip(label:Text('إيجار'),selected:false),ChoiceChip(label:Text('فيلا'),selected:true),ChoiceChip(label:Text('شقة'),selected:false),ChoiceChip(label:Text('صنعاء'),selected:true)]),const SizedBox(height:18),const Text('نطاق السعر',style:TextStyle(fontWeight:FontWeight.w800)),const RangeSlider(values:RangeValues(25,90),min:0,max:120,onChanged:null),const SizedBox(height:10),FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('عرض النتائج'))])));

class MapPage extends StatelessWidget{const MapPage({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الخريطة')),body:const MapBody());}
class MapBody extends StatelessWidget{const MapBody({super.key});@override Widget build(BuildContext c)=>Stack(children:[Container(color:const Color(0xFFECEFEC),child:CustomPaint(painter:MapPaint(),child:const SizedBox.expand())),const Positioned(top:130,right:45,child:_Price('85م')),const Positioned(top:230,left:55,child:_Price('58م')),const Positioned(top:340,right:115,child:_Price('42.5م')),Positioned(bottom:18,left:16,right:16,child:PropCard(ps[0]))]);}
class _Price extends StatelessWidget{final String t;const _Price(this.t);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(horizontal:11,vertical:7),decoration:BoxDecoration(color:deep,borderRadius:BorderRadius.circular(11)),child:Text(t,style:const TextStyle(color:Colors.white,fontWeight:FontWeight.w900)));}
class MapPaint extends CustomPainter{@override void paint(Canvas can,Size s){final a=Paint()..color=Colors.white..strokeWidth=6;for(int i=1;i<7;i++){can.drawLine(Offset(0,s.height*i/7),Offset(s.width,s.height*i/7-20),a);}for(int i=1;i<6;i++){can.drawLine(Offset(s.width*i/6,0),Offset(s.width*i/6+30,s.height),a);}}@override bool shouldRepaint(covariant CustomPainter o)=>false;}

class Details extends StatelessWidget{final P p;const Details(this.p,{super.key});@override Widget build(BuildContext c)=>Scaffold(body:CustomScrollView(slivers:[SliverAppBar(expandedHeight:300,pinned:true,actions:[IconButton(onPressed:(){},icon:const Icon(Icons.favorite_border)),IconButton(onPressed:(){},icon:const Icon(Icons.share_outlined))],flexibleSpace:FlexibleSpaceBar(background:Img(p.img))),SliverPadding(padding:const EdgeInsets.fromLTRB(18,18,18,110),sliver:SliverList.list(children:[Row(children:[Expanded(child:Text(p.t,style:const TextStyle(fontSize:23,fontWeight:FontWeight.w900))),Tag(p.purpose)]),const SizedBox(height:7),Text(p.p,style:const TextStyle(color:green,fontWeight:FontWeight.w900,fontSize:20)),const SizedBox(height:4),Text(p.l,style:const TextStyle(color:muted)),const SizedBox(height:18),Row(children:[Expanded(child:_Fact(Icons.home_work_outlined,p.type)),const SizedBox(width:8),Expanded(child:_Fact(Icons.square_foot_outlined,'12 لبنة')),const SizedBox(width:8),Expanded(child:_Fact(Icons.bed_outlined,'5 غرف'))]),const SizedBox(height:14),Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:const Color(0xFFFFF7E4),borderRadius:BorderRadius.circular(18)),child:Row(children:[const Icon(Icons.handshake_outlined,color:Color(0xFF8A6413)),const SizedBox(width:10),Expanded(child:Text(p.sai,style:const TextStyle(fontWeight:FontWeight.w900,color:Color(0xFF6E571A))))])),const SizedBox(height:22),const _Title('عن العقار'),const SizedBox(height:7),const Text('عقار بموقع مميز وتشطيب حديث، قريب من الخدمات والطرق الرئيسية. البيانات هنا تجريبية فقط لعرض الشكل النهائي المحتمل.',style:TextStyle(color:muted,height:1.7)),const SizedBox(height:22),const _Title('أدوات القرار'),const SizedBox(height:10),Row(children:[Expanded(child:_Tile(Icons.insights_outlined,'مؤشرات الأسعار',()=>go(c,const Market()))),const SizedBox(width:10),Expanded(child:_Tile(Icons.compare_arrows,'المقارنة',()=>go(c,const Compare())))]),const SizedBox(height:22),const _Title('عقارات مشابهة'),const SizedBox(height:10),...ps.skip(1).take(2).map((x)=>Padding(padding:const EdgeInsets.only(bottom:10),child:PropCard(x)))]))]),bottomSheet:SafeArea(child:Container(padding:const EdgeInsets.all(12),color:Colors.white,child:Row(children:[Expanded(child:OutlinedButton.icon(onPressed:()=>go(c,Chat(p)),icon:const Icon(Icons.chat_bubble_outline),label:const Text('مراسلة'))),const SizedBox(width:8),Expanded(child:FilledButton.icon(onPressed:()=>go(c,Booking(p)),icon:const Icon(Icons.calendar_month_outlined),label:const Text('طلب معاينة')))]))));}
class _Fact extends StatelessWidget{final IconData i;final String t;const _Fact(this.i,this.t);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(vertical:13),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(16),border:Border.all(color:line)),child:Column(children:[Icon(i,color:green),const SizedBox(height:5),Text(t,style:const TextStyle(fontWeight:FontWeight.w800,fontSize:11))]));}
class _Tile extends StatelessWidget{final IconData i;final String t;final VoidCallback f;const _Tile(this.i,this.t,this.f);@override Widget build(BuildContext c)=>InkWell(onTap:f,child:Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Icon(i,color:green),const SizedBox(height:8),Text(t,style:const TextStyle(fontWeight:FontWeight.w900))])));}

class Favorites extends StatelessWidget{const Favorites({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('المفضلة'),actions:[TextButton(onPressed:()=>go(c,const Compare()),child:const Text('مقارنة'))]),body:ListView.separated(padding:const EdgeInsets.all(16),itemCount:3,separatorBuilder:(_,__)=>const SizedBox(height:10),itemBuilder:(c,i)=>PropCard(ps[i])));}
class Compare extends StatelessWidget{const Compare({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('مقارنة العقارات')),body:ListView(padding:const EdgeInsets.all(16),children:[Row(children:[Expanded(child:PropCard(ps[0],big:true)),const SizedBox(width:8),Expanded(child:PropCard(ps[3],big:true))]),const SizedBox(height:18),...['السعر','الموقع','النوع','المساحة','الغرف','السعي'].map((x)=>ListTile(contentPadding:EdgeInsets.zero,title:Text(x,style:const TextStyle(color:muted,fontSize:12)),subtitle:Row(children:[Expanded(child:Text(x=='السعر'?ps[0].p:x=='الموقع'?ps[0].l:x=='السعي'?ps[0].sai:'بيانات العقار',style:const TextStyle(fontWeight:FontWeight.w800))),Expanded(child:Text(x=='السعر'?ps[3].p:x=='الموقع'?ps[3].l:x=='السعي'?ps[3].sai:'بيانات العقار',style:const TextStyle(fontWeight:FontWeight.w800)))]) ))]));}
class Market extends StatelessWidget{const Market({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('مؤشرات الأسعار')),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(18),decoration:BoxDecoration(gradient:const LinearGradient(colors:[green,deep]),borderRadius:BorderRadius.circular(24)),child:const Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('فلل للبيع · صنعاء · حدة',style:TextStyle(color:Colors.white70)),SizedBox(height:7),Text('متوسط السعر في العينات المشابهة',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:18)),SizedBox(height:4),Text('82,400,000 ر.ي',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:28))])),const SizedBox(height:16),Row(children:const [Expanded(child:_Stat('8','عقارات مقارنة')),SizedBox(width:8),Expanded(child:_Stat('76–92م','نطاق الأسعار')),SizedBox(width:8),Expanded(child:_Stat('10.5','متوسط اللبن'))]),const SizedBox(height:20),const Text('بيانات تجريبية مبنية على عقارات منشورة ومتشابهة لعرض شكل الأداة فقط.',style:TextStyle(color:muted,height:1.6)),const SizedBox(height:14),...ps.take(3).map((x)=>Padding(padding:const EdgeInsets.only(bottom:10),child:PropCard(x)))]));}
class _Stat extends StatelessWidget{final String a,b;const _Stat(this.a,this.b);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.symmetric(vertical:15,horizontal:6),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(17),border:Border.all(color:line)),child:Column(children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w900,color:deep)),const SizedBox(height:3),Text(b,textAlign:TextAlign.center,style:const TextStyle(color:muted,fontSize:10))]));}

class SavedSearches extends StatelessWidget{const SavedSearches({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('عمليات البحث المحفوظة')),body:ListView(padding:const EdgeInsets.all(16),children:const [_Saved('فلل للبيع في حدة','60–100 مليون · 5 غرف أو أكثر',true),SizedBox(height:10),_Saved('شقق للإيجار','صنعاء · حتى 400 ألف · 3 غرف',true),SizedBox(height:10),_Saved('أراضي سكنية','شملان · 10 لبن أو أكثر',false)]));}
class _Saved extends StatelessWidget{final String a,b;final bool on;const _Saved(this.a,this.b,this.on);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[const Icon(Icons.bookmark_outline,color:green),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(b,style:const TextStyle(color:muted,fontSize:11))])),Switch(value:on,onChanged:(_){})]));}

class Messages extends StatelessWidget{const Messages({super.key});@override Widget build(BuildContext c)=>SafeArea(child:Column(children:[const Padding(padding:EdgeInsets.fromLTRB(18,18,18,10),child:Row(children:[Expanded(child:Text('الرسائل',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900))),Icon(Icons.search)])),Expanded(child:ListView.separated(padding:const EdgeInsets.symmetric(horizontal:18),itemCount:3,separatorBuilder:(_,__)=>const Divider(color:line),itemBuilder:(c,i)=>ListTile(onTap:()=>go(c,Chat(ps[i])),contentPadding:const EdgeInsets.symmetric(vertical:8),leading:ClipRRect(borderRadius:BorderRadius.circular(12),child:Img(ps[i].img,w:58,h:58)),title:Text(i==0?'مكتب النخبة العقاري':i==1?'أحمد عبدالله':'مؤسسة الأمانة',style:const TextStyle(fontWeight:FontWeight.w900)),subtitle:Text(i==0?'تم تأكيد معاينتك غدًا الساعة 4:30 م':i==1?'هل يناسبك الموعد يوم الثلاثاء؟':'أرسلت لك تفاصيل الموقع',maxLines:1,overflow:TextOverflow.ellipsis),trailing:i==0?const CircleAvatar(radius:11,backgroundColor:green,child:Text('2',style:TextStyle(color:Colors.white,fontSize:10))):null)))]));}
class Chat extends StatelessWidget{final P p;const Chat(this.p,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('مكتب النخبة العقاري')),body:Column(children:[Container(margin:const EdgeInsets.all(12),padding:const EdgeInsets.all(10),decoration:BoxDecoration(color:const Color(0xFFEAF5F2),borderRadius:BorderRadius.circular(16)),child:Row(children:[const Icon(Icons.home_work_outlined,color:green),const SizedBox(width:8),Expanded(child:Text(p.t,style:const TextStyle(fontWeight:FontWeight.w900))),Text(p.p,style:const TextStyle(color:green,fontWeight:FontWeight.w900,fontSize:11))])),Expanded(child:ListView(padding:const EdgeInsets.all(16),children:const [_B('السلام عليكم، هل العقار ما زال متاحًا؟',true),_B('وعليكم السلام، نعم متاح ويمكن ترتيب معاينة.',false),_B('ممتاز، يناسبني غدًا بعد العصر.',true),_B('تم إرسال مقترح معاينة الساعة 4:30 م.',false)])),SafeArea(child:Padding(padding:const EdgeInsets.all(10),child:Row(children:[Expanded(child:TextField(decoration:const InputDecoration(hintText:'اكتب رسالة...'))),const SizedBox(width:8),FloatingActionButton.small(onPressed:(){},backgroundColor:green,child:const Icon(Icons.send,color:Colors.white))]))) ]));}
class _B extends StatelessWidget{final String t;final bool mine;const _B(this.t,this.mine);@override Widget build(BuildContext c)=>Align(alignment:mine?Alignment.centerRight:Alignment.centerLeft,child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(12),constraints:BoxConstraints(maxWidth:MediaQuery.of(c).size.width*.75),decoration:BoxDecoration(color:mine?green:Colors.white,borderRadius:BorderRadius.circular(16),border:mine?null:Border.all(color:line)),child:Text(t,style:TextStyle(color:mine?Colors.white:deep,height:1.5,fontWeight:FontWeight.w600))));}

class Viewings extends StatelessWidget{const Viewings({super.key});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Text('المعاينات',style:TextStyle(fontSize:28,fontWeight:FontWeight.w900)),const SizedBox(height:6),const Text('كل المواعيد والإجراءات المطلوبة',style:TextStyle(color:muted)),const SizedBox(height:18),Row(children:const [Expanded(child:_Stat('2','قادمة')),SizedBox(width:8),Expanded(child:_Stat('1','تحتاج إجراء')),SizedBox(width:8),Expanded(child:_Stat('3','مكتملة'))]),const SizedBox(height:20),_V(ps[0],'بانتظار تأكيدك','غدًا · 4:30 م'),const SizedBox(height:12),_V(ps[1],'مؤكدة','الثلاثاء · 11:00 ص'),const SizedBox(height:12),_V(ps[3],'مكتملة','8 سبتمبر · 5:00 م')]));}
class _V extends StatelessWidget{final P p;final String s,t;const _V(this.p,this.s,this.t);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(13),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:line)),child:Column(children:[Row(children:[ClipRRect(borderRadius:BorderRadius.circular(12),child:Img(p.img,w:82,h:76)),const SizedBox(width:10),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(p.t,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(t,style:const TextStyle(color:muted,fontSize:11))])),Tag(s)]),const SizedBox(height:11),Row(children:[Expanded(child:OutlinedButton(onPressed:()=>go(c,Chat(p)),child:const Text('فتح المحادثة'))),const SizedBox(width:8),Expanded(child:FilledButton(onPressed:()=>go(c,Booking(p)),child:Text(s=='بانتظار تأكيدك'?'تأكيد':'التفاصيل')))])]));}
class Booking extends StatelessWidget{final P p;const Booking(this.p,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('طلب معاينة')),body:ListView(padding:const EdgeInsets.all(18),children:[PropCard(p),const SizedBox(height:18),const Text('اختر الموعد المناسب',style:TextStyle(fontWeight:FontWeight.w900,fontSize:21)),const SizedBox(height:12),Wrap(spacing:8,runSpacing:8,children:const [ChoiceChip(label:Text('الأحد 13'),selected:false),ChoiceChip(label:Text('الاثنين 14'),selected:true),ChoiceChip(label:Text('الثلاثاء 15'),selected:false),ChoiceChip(label:Text('10:00 ص'),selected:false),ChoiceChip(label:Text('4:30 م'),selected:true),ChoiceChip(label:Text('6:00 م'),selected:false)]),const SizedBox(height:18),const TextField(maxLines:3,decoration:InputDecoration(labelText:'ملاحظة اختيارية')),const SizedBox(height:18),FilledButton(onPressed:()=>ok(c,'تم إرسال طلب المعاينة التجريبي'),child:const Text('إرسال الطلب'))]));}

class Journey extends StatelessWidget{const Journey({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('رحلتي العقارية')),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(16),decoration:BoxDecoration(color:deep,borderRadius:BorderRadius.circular(22)),child:Row(children:[ClipRRect(borderRadius:BorderRadius.circular(14),child:Img(ps[0].img,w:84,h:84)),const SizedBox(width:12),const Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('رحلتك الحالية',style:TextStyle(color:Colors.white70)),SizedBox(height:3),Text('فيلا عصرية في حدة',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:17)),SizedBox(height:5),Text('مرحلة الاتفاق',style:TextStyle(color:Color(0xFFA9E2D2),fontWeight:FontWeight.w800))]))])),const SizedBox(height:18),const _Step('حفظ العقار','تمت الإضافة للمفضلة',true),const _Step('بدء المحادثة','المحادثة نشطة',true),const _Step('المعاينة','مكتملة · 8 سبتمبر',true),_Step('الاتفاق','بانتظار رد الطرف الآخر',false,onTap:()=>go(c,const Agreement())),_Step('العقد','يظهر بعد اكتمال الاتفاق',false,onTap:()=>go(c,const Contract()))]));}
class _Step extends StatelessWidget{final String a,b;final bool done;final VoidCallback? onTap;const _Step(this.a,this.b,this.done,{this.onTap});@override Widget build(BuildContext c)=>InkWell(onTap:onTap,child:Container(margin:const EdgeInsets.only(bottom:9),padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[CircleAvatar(backgroundColor:done?const Color(0xFFEAF5F2):bg,child:Icon(done?Icons.check:Icons.circle_outlined,color:done?green:muted)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w900)),Text(b,style:const TextStyle(color:muted,fontSize:11))])),if(onTap!=null)const Icon(Icons.arrow_back_ios_new,size:15,color:muted)])));}
class Agreement extends StatelessWidget{const Agreement({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الاتفاق')),body:ListView(padding:const EdgeInsets.all(16),children:const [_Info('الحالة',[('الحالة','بانتظار رد الطرف الآخر'),('آخر تحديث','اليوم 1:20 ص')]),SizedBox(height:10),_Info('عرضك الحالي',[('السعر المقترح','82,000,000 ر.ي'),('السعي','1% · على المشتري'),('صلاحية العرض','48 ساعة')]),SizedBox(height:10),_Info('سجل التعديلات',[('الإصدار 3','82 مليون · أنت'),('الإصدار 2','84 مليون · الطرف الآخر'),('الإصدار 1','80 مليون · أنت')]) ]));}
class Contract extends StatelessWidget{const Contract({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('عقد الإيجار')),body:ListView(padding:const EdgeInsets.all(16),children:const [_Info('حالة العقد',[('الحالة','مسودة داخل التطبيق'),('العقار','شقة واسعة قرب شارع الخمسين'),('المدة','12 شهرًا')]),SizedBox(height:10),_Info('الشروط',[('الإيجار الشهري','350,000 ر.ي'),('السعي','20% من شهر · على المستأجر'),('تاريخ البداية','1 أكتوبر 2026')]),SizedBox(height:14),Text('هذه الشاشة تجريبية لعرض التنظيم فقط ولا تمثل توثيقًا قانونيًا أو رسميًا.',style:TextStyle(color:muted,height:1.6))]));}
class _Info extends StatelessWidget{final String t;final List<(String,String)> r;const _Info(this.t,this.r);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(15),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)),const SizedBox(height:8),...r.map((x)=>Padding(padding:const EdgeInsets.symmetric(vertical:6),child:Row(children:[Expanded(child:Text(x.$1,style:const TextStyle(color:muted,fontSize:11))),Expanded(flex:2,child:Text(x.$2,style:const TextStyle(fontWeight:FontWeight.w800)))]) )]));}

class Notifications extends StatelessWidget{const Notifications({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الإشعارات')),body:ListView(padding:const EdgeInsets.all(16),children:const [_Note(Icons.calendar_month_outlined,'تم تأكيد المعاينة','موعد فيلا عصرية في حدة غدًا الساعة 4:30 م'),SizedBox(height:9),_Note(Icons.price_change_outlined,'تغير سعر عقار في المفضلة','انخفض السعر من 88 إلى 85 مليون ر.ي'),SizedBox(height:9),_Note(Icons.bookmark_outline,'عقار جديد يطابق بحثك','فيلا جديدة في حدة ضمن نطاق السعر المحفوظ'),SizedBox(height:9),_Note(Icons.chat_bubble_outline,'رسالة جديدة','مكتب النخبة: تم إرسال مقترح معاينة')]));}
class _Note extends StatelessWidget{final IconData i;final String a,b;const _Note(this.i,this.a,this.b);@override Widget build(BuildContext c)=>Container(padding:const EdgeInsets.all(14),decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(18),border:Border.all(color:line)),child:Row(children:[CircleAvatar(backgroundColor:const Color(0xFFEAF5F2),child:Icon(i,color:green)),const SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(a,style:const TextStyle(fontWeight:FontWeight.w900)),const SizedBox(height:3),Text(b,style:const TextStyle(color:muted,fontSize:11))]))]));}

class Account extends StatelessWidget{const Account({super.key});@override Widget build(BuildContext c)=>SafeArea(child:ListView(padding:const EdgeInsets.all(18),children:[const Row(children:[CircleAvatar(radius:32,backgroundColor:Color(0xFFEAF5F2),child:Icon(Icons.person,color:green,size:30)),SizedBox(width:12),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('محمد أحمد',style:TextStyle(fontSize:21,fontWeight:FontWeight.w900)),Text('+967 777 123 456',style:TextStyle(color:muted)),Text('حساب مستخدم',style:TextStyle(color:green,fontWeight:FontWeight.w800,fontSize:11))]))]),const SizedBox(height:18),_Menu('نشاطي',[('رحلتي العقارية',Icons.route_outlined),('المفضلة',Icons.favorite_border),('المقارنة',Icons.compare_arrows),('البحث المحفوظ',Icons.bookmark_outline),('الإشعارات',Icons.notifications_none)],c),const SizedBox(height:14),_Menu('الحساب والإعدادات',[('البيانات الشخصية',Icons.person_outline),('تفضيلات الإشعارات',Icons.tune),('الدعم والمساعدة',Icons.support_agent_outlined),('الخصوصية والأمان',Icons.shield_outlined),('شاشة تسجيل الدخول',Icons.login)],c)]));}
class _Menu extends StatelessWidget{final String t;final List<(String,IconData)> xs;final BuildContext root;const _Menu(this.t,this.xs,this.root);@override Widget build(BuildContext c)=>Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text(t,style:const TextStyle(fontWeight:FontWeight.w900,fontSize:17)),const SizedBox(height:8),Container(decoration:BoxDecoration(color:Colors.white,borderRadius:BorderRadius.circular(20),border:Border.all(color:line)),child:Column(children:List.generate(xs.length,(i){final x=xs[i];return Column(children:[ListTile(leading:Icon(x.$2,color:deep),title:Text(x.$1,style:const TextStyle(fontWeight:FontWeight.w800)),trailing:const Icon(Icons.arrow_back_ios_new,size:14),onTap:()=>openMenu(root,x.$1)),if(i<xs.length-1)const Divider(height:1,color:line,indent:16,endIndent:60)]);}))) ]);}
void openMenu(BuildContext c,String x){if(x=='رحلتي العقارية')go(c,const Journey());else if(x=='المفضلة')go(c,const Favorites());else if(x=='المقارنة')go(c,const Compare());else if(x=='البحث المحفوظ')go(c,const SavedSearches());else if(x=='الإشعارات')go(c,const Notifications());else if(x=='تفضيلات الإشعارات')go(c,const Prefs());else if(x=='الدعم والمساعدة')go(c,const Support());else if(x=='شاشة تسجيل الدخول')go(c,const Login());else go(c,SimplePage(x));}

class Prefs extends StatefulWidget{const Prefs({super.key});@override State<Prefs> createState()=>_PrefsState();}
class _PrefsState extends State<Prefs>{bool a=true,b=true,d=true,e=true;@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('تفضيلات الإشعارات')),body:ListView(children:[SwitchListTile(value:a,onChanged:(v)=>setState(()=>a=v),title:const Text('نتائج البحث المحفوظ')),SwitchListTile(value:b,onChanged:(v)=>setState(()=>b=v),title:const Text('تغير الأسعار')),SwitchListTile(value:d,onChanged:(v)=>setState(()=>d=v),title:const Text('الرسائل')),SwitchListTile(value:e,onChanged:(v)=>setState(()=>e=v),title:const Text('المعاينات')),const ListTile(leading:Icon(Icons.lock_outline,color:green),title:Text('إشعارات الأمان'),subtitle:Text('إشعارات حرجة ولا يمكن تعطيلها'),trailing:Icon(Icons.check_circle,color:green))]));}
class Support extends StatelessWidget{const Support({super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:const Text('الدعم والمساعدة')),body:ListView(padding:const EdgeInsets.all(16),children:[Container(padding:const EdgeInsets.all(17),decoration:BoxDecoration(color:deep,borderRadius:BorderRadius.circular(21)),child:const Row(children:[Icon(Icons.support_agent,color:Colors.white,size:32),SizedBox(width:11),Expanded(child:Column(crossAxisAlignment:CrossAxisAlignment.start,children:[Text('كيف نقدر نساعدك؟',style:TextStyle(color:Colors.white,fontWeight:FontWeight.w900,fontSize:18)),Text('افتح تذكرة أو تابع الطلبات السابقة',style:TextStyle(color:Colors.white70))]))])),const SizedBox(height:14),FilledButton.icon(onPressed:()=>ok(c,'تم إنشاء تذكرة تجريبية'),icon:const Icon(Icons.add),label:const Text('فتح تذكرة جديدة')),const SizedBox(height:16),const _Info('تذاكري',[('#S-1048','استفسار عن حالة معاينة · قيد المعالجة'),('#S-1032','بلاغ عن إعلان غير متاح · مكتملة')]) ]));}
class SimplePage extends StatelessWidget{final String t;const SimplePage(this.t,{super.key});@override Widget build(BuildContext c)=>Scaffold(appBar:AppBar(title:Text(t)),body:ListView(padding:const EdgeInsets.all(16),children:[_Info(t,const [('الحالة','بيانات تجريبية'),('الغرض','عرض شكل وتنظيم الشاشة')]),const SizedBox(height:14),const TextField(decoration:InputDecoration(labelText:'الاسم / البيانات')),const SizedBox(height:10),const TextField(decoration:InputDecoration(labelText:'معلومة إضافية')),const SizedBox(height:16),FilledButton(onPressed:()=>ok(c,'تم حفظ البيانات التجريبية'),child:const Text('حفظ'))]));}
class Login extends StatelessWidget{const Login({super.key});@override Widget build(BuildContext c)=>Scaffold(body:SafeArea(child:Padding(padding:const EdgeInsets.all(22),child:Column(crossAxisAlignment:CrossAxisAlignment.stretch,children:[IconButton(alignment:Alignment.centerRight,onPressed:()=>Navigator.pop(c),icon:const Icon(Icons.close)),const Spacer(),Container(width:72,height:72,alignment:Alignment.center,decoration:BoxDecoration(color:green,borderRadius:BorderRadius.circular(24)),child:const Icon(Icons.home_work_outlined,color:Colors.white,size:34)),const SizedBox(height:20),const Text('مرحبًا بك',style:TextStyle(fontSize:30,fontWeight:FontWeight.w900)),const SizedBox(height:5),const Text('أدخل رقم هاتفك للمتابعة',style:TextStyle(color:muted)),const SizedBox(height:22),const TextField(keyboardType:TextInputType.phone,decoration:InputDecoration(labelText:'رقم الهاتف',prefixText:'+967  ')),const SizedBox(height:12),FilledButton(onPressed:()=>ok(c,'هذه شاشة تجريبية فقط'),child:const Text('متابعة')),const Spacer(flex:2),const Text('نموذج بصري تجريبي — لا يتم إرسال أي بيانات',textAlign:TextAlign.center,style:TextStyle(color:muted,fontSize:10))]))));}

void ok(BuildContext c,String t)=>showDialog(context:c,builder:(_)=>AlertDialog(icon:const Icon(Icons.check_circle,color:green,size:42),title:const Text('تم بنجاح',textAlign:TextAlign.center),content:Text(t,textAlign:TextAlign.center),actionsAlignment:MainAxisAlignment.center,actions:[FilledButton(onPressed:()=>Navigator.pop(c),child:const Text('حسنًا'))]));
